# Databricks notebook source
# MAGIC %md 
# MAGIC Please keep in mind that this require an installation on a cluster. then you will not be able to run it unless you have those permissions.

# COMMAND ----------

!pip install bamboolib==1.30.17

# COMMAND ----------

import bamboolib as bam

# COMMAND ----------

bam

# COMMAND ----------

# MAGIC %md 
# MAGIC ### Code purely generated by Bamboolib 

# COMMAND ----------

import plotly.express as px
fig = px.scatter(df, x='order_date', y='total_profit', size='units_sold', color='sales_channel')
fig

# COMMAND ----------

import plotly.express as px
fig = px.scatter(df, x='order_date', y='total_profit', size='unit_price', color='sales_channel')
fig

# COMMAND ----------

import plotly.express as px
fig = px.scatter(df, x='order_date', y='total_profit', size='units_sold', color='sales_channel', facet_row='order_prio')
fig

# COMMAND ----------

import plotly.express as px
fig = px.histogram(df, x='total_revenue')
fig

# COMMAND ----------

import pandas as pd; import numpy as np
df = pd.read_csv(bam.sales_csv)
# Step: Change data type of item_type to String/Text
df['item_type'] = df['item_type'].astype('string')

# Step: Change data type of country to String/Text
df['country'] = df['country'].astype('string')

# Step: Change data type of region to String/Text
df['region'] = df['region'].astype('string')

# Step: Change data type of sales_channel to String/Text
df['sales_channel'] = df['sales_channel'].astype('string')

# Step: Change data type of order_date to Datetime
df['order_date'] = pd.to_datetime(df['order_date'], infer_datetime_format=True)

# Step: Change data type of ship_date to Datetime
df['ship_date'] = pd.to_datetime(df['ship_date'], infer_datetime_format=True)

# COMMAND ----------


